site_name: Resepi 101
nav:
    - Home: index.md
    - About: about.md
    - Recipe:
        - Chickenrice: 'rec/chickenrice.md'
        - Chickengarlic: 'rec/chickengar.md'
    - Appreciation: appr.md
theme: readthedocs
