site_name: Resepi 101
nav:
    - Home: index.md
    - About: about.md
    - Chicken Recipe:
        - Chicken Soup: rec/chickensoup.md
        - Chicken Rice: rec/chickenrice.md
        - Chicken Garlic: rec/chickengar.md
    - Fish Recipe:
        - Fish Sambal: fishrec/fishsambal.md
        - Steamed Fish: fishrec/fishsteam.md
    - Appreciation: appr.md
theme: material
plugins:
  - search
  - section-index
