site_name: Cash.io
nav:
    - Home: index.md
    - About: about.md
    - Getting Started:
        - Manage Cards: rec/chickensoup.md
        - Manage Accounts: rec/chickenrice.md
        - Send and Receive Money: rec/chickengar.md
    - Manage Payment:
        - Pay Bills: fishrec/fishsambal.md
        - QR Code Payment: fishrec/fishsteam.md
    - FAQs: appr.md
theme: material
plugins:
  - search
